name: Docker Image CI

on:
  schedule:
  - cron: "0 2 * * *"
  push:
    branches:
    - main
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'
    - uses: denoland/setup-deno@v1
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Get latest Node version
      id: node-version
      run: echo "VERSION=$(node --version)" >> "$GITHUB_OUTPUT"
    - name: Get latest Deno version
      id: deno-version
      run: echo "VERSION=$(deno -V | grep -oE '[^ ]+$')" >> "$GITHUB_OUTPUT"
    - name: Check if version exists on hub
      id: docker-version
      run: curl -s "https://hub.docker.com/v2/repositories/halvardm/deno-node/tags/${{ steps.node-version.outputs.VERSION }}-${{ steps.deno-version.outputs.VERSION }}/" | jq '.name'
    - run: echo "${{ steps.node-version.outputs.VERSION }} - ${{ steps.deno-version.outputs.VERSION }} - ${{ steps.docker-version.outputs.VERSION }}"

#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
