name: Schedule CI

on:
  schedule:
    - cron: "13 5 * * *"
  push:
    branches:
      - main

jobs:
  base:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ubuntu-base
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get latest ubuntu version
        id: ubuntu-version
        run: echo "VERSION=$(curl -sL https://changelogs.ubuntu.com/meta-release-lts | grep 'Version:' | tail -n1 | cut -d' ' -f2)" >> "$GITHUB_OUTPUT"
      - name: Get image version
        id: image-version
        run: echo "VERSION=${{ steps.ubuntu-version.outputs.VERSION }}" >> "$GITHUB_OUTPUT"
      - name: Check if version exists on hub
        id: docker-version
        run: echo "VERSION=$(curl -s 'https://hub.docker.com/v2/repositories/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}/tags/${{ steps.image-version.outputs.VERSION }}/' | jq -r '.name')" >> "$GITHUB_OUTPUT"
      - run: echo "Image version ${{ steps.image-version.outputs.VERSION }}, Ubuntu version ${{ steps.ubuntu-version.outputs.VERSION }}, Docker version ${{ steps.docker-version.outputs.VERSION }}"
      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        if: (steps.docker-version.outputs.VERSION != steps.image-version.outputs.VERSION) || contains(github.event.head_commit.message, '[force]')
        with:
          context: ./${{ env.IMAGE_NAME }}
          pull: true
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.image-version.outputs.VERSION }}

  deno-node:
    needs: base
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: deno-node
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - uses: denoland/setup-deno@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get latest Node version
        id: node-version
        run: echo "VERSION=$(node --version | grep -oE '[^v].*$')" >> "$GITHUB_OUTPUT"
      - name: Get latest Deno version
        id: deno-version
        run: echo "VERSION=$(deno -V | grep -oE '[^ ]+$')" >> "$GITHUB_OUTPUT"
      - name: Get image version
        id: image-version
        run: echo "VERSION=${{ steps.node-version.outputs.VERSION }}-${{ steps.deno-version.outputs.VERSION }}" >> "$GITHUB_OUTPUT"
      - name: Check if version exists on hub
        id: docker-version
        run: echo "VERSION=$(curl -s 'https://hub.docker.com/v2/repositories/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}/tags/${{ steps.image-version.outputs.VERSION }}/' | jq -r '.name')" >> "$GITHUB_OUTPUT"
      - run: echo "Image version ${{ steps.image-version.outputs.VERSION }}, Node version ${{ steps.node-version.outputs.VERSION }}, Deno version ${{ steps.deno-version.outputs.VERSION }}, Docker version ${{ steps.docker-version.outputs.VERSION }}"
      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        if: (steps.docker-version.outputs.VERSION != steps.image-version.outputs.VERSION) || contains(github.event.head_commit.message, '[force]')
        with:
          context: ./${{ env.IMAGE_NAME }}
          pull: true
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.image-version.outputs.VERSION }}
